# Generated by Django 3.1.1 on 2020-09-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classNumber', models.CharField(db_index=True, max_length=20, unique=True)),
                ('grade', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(db_index=True, max_length=20)),
                ('college', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('sex', models.IntegerField(default=0)),
                ('classNumber', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(db_index=True, max_length=20)),
                ('state', models.IntegerField(default=0)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField(auto_now=True)),
                ('points', models.DecimalField(decimal_places=5, max_digits=10)),
                ('duration', models.DecimalField(decimal_places=5, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('classNumber', models.CharField(db_index=True, max_length=20, unique=True)),
                ('grade', models.CharField(db_index=True, max_length=20)),
                ('college', models.CharField(db_index=True, max_length=20)),
            ],
        ),
    ]
