# Generated by Django 3.1.1 on 2020-09-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specificApis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='studentId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='college',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='StudentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specificApis.student'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specificApis.grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specificApis.classes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='classNumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specificApis.classes'),
        ),
    ]
