# Generated by Django 3.1.1 on 2020-09-21 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specificApis', '0003_auto_20200921_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='StudentId',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='studentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specificApis.student', to_field='studentId'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='classNumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specificApis.user', to_field='classNumber'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specificApis.grade', to_field='grade'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='classNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specificApis.classes', to_field='classNumber'),
        ),
    ]
