# Generated by Django 3.1.1 on 2020-10-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specificApis', '0006_auto_20200923_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='initPoints',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
