# Generated by Django 3.1.1 on 2021-01-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specificApis', '0009_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='gradeAdmin',
            field=models.ForeignKey(default='admin2018', on_delete=django.db.models.deletion.CASCADE, to='specificApis.administrator', to_field='username'),
            preserve_default=False,
        ),
    ]
