# Generated by Django 3.1.1 on 2021-01-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specificApis', '0011_auto_20210123_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeadmin',
            name='types',
        ),
    ]
