# Generated by Django 3.1.1 on 2021-02-02 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specificApis', '0013_auto_20210124_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('pointsPerHour', models.FloatField(default=1.0)),
                ('requiredPoints', models.IntegerField(default=160)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='classNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specificApis.classes', to_field='classNumber'),
        ),
    ]
